### PR TITLE
Make shadow selectable via menu

### PR DESCRIPTION
**Pull request by ghost**
This makes the shadow selectable via the "Aircraft options" in the menu

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@D-ECHO sorry for my late review, I have been super busy with the c172p. So:
- why is the shadow completely dark and not half transparent like in the c172p?
- what are these white spots in the shadow?
  fgfs-screen-002
- I think the shadow should be raised substantially in the z-axis, see this view here, half of it is under the ground!
  fgfs-screen-001
- finally, do we really need a checkbox for enabling/disabling the shadow? Shouldn't it just be enabled and that's it? Our menu has already so many options, and with many more to come it's getting very cluttered there

**Comment by ghost** [comment]
With this commit, the shadow is now half transparent and also the strange spots should be gone. In my opinion, it's good to have this checkbox, mainly because the shadow is still buggy and some might prefer not to see it at all.

**Comment by ghost** [comment]
Btw @Harald67 @gilbertohasnofb are you still on this project?

**Comment by gilbertohasnofb** [comment]
@D-ECHO I am a bit away from FlightGear recently, RL has been hectic. But I am happy to help in the project if something comes up, I might just not be very quick doing it.

**Comment by ghost** [comment]
okay fine! Any reasons not to merge this PR?

**Comment by gilbertohasnofb** [comment]
sorry @D-ECHO, I did not have the chance to test it before. Looks all good to me.

**Comment by ghost** [comment]
Thank you :)

**Pull request merged**
