### PR TITLE
new compass

### LINKED ISSUE #7: Compass too small
The compass is too small, compare this:

With this:

c150-5

Also note that the compass has a cable going to the roof of the plane, which is also missing

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
New compass model

Closes #7

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
:warning: :warning: :warning: 

@Harald67 please do not merge yet, we first have to remove the old compass model from the .ac file. See: https://github.com/Harald67/c150/issues/7#issuecomment-236436475

**Comment by Harald67** [comment]
I've done other changes to the model so I can not push the model with just the compass removed.

**Comment by gilbertohasnofb** [comment]
I don't  understand what you mean. Did you modify the ac model in the branch `bug-7`? Let me know if I can be of any help with this, Harald.

**Comment by gilbertohasnofb** [comment]
Oh, I see you fixed it directly in the `master`. No problems, thanks for the help on this issue!

**Pull request merged**
