### PR TITLE
New starter system, split lever sound

### PR DESCRIPTION
**Pull request by ghost**
Request to merge ;)
Could you cut out the breakers and give them the names according to the code and then uncomment teh code? That should make them work ;)

### CODE REVIEW

**Comment by Harald67** [comment]
I've not yet merged the pull request, but I think there are some problems:
- is the starter key working as before ? I think I will not turn to the right when pressing 's' (but this is not really clear for me).
- you added a second master-alt pick animation instead of changing the already existing one.
- you've redefined the 's' key, but this should be done with a redefinition of the controls.startEngine() nasal function instead so that the engine can be started with any hardware interface.
- if you change the engine sound then you must adapt the picth so that it matches the rpm.
- i'm not sure why you changed the empty weight (even if there are numbers around 1060 floating around), you must not forget the weight of the equipment (radios, etc.).

**Comment by ghost** [comment]
**_is the starter key working as before ? I think I will not turn to the right when pressing 's' (but this is not really clear for me).
-> Sorry, that's a bug I forgot, will fix in the next commit
you added a second master-alt pick animation instead of changing the already existing one.
-> should be changed in         431a6f0  was beginning of breaker code
you've redefined the 's' key, but this should be done with a redefinition of the controls.startEngine() nasal function instead so that the engine can be started with any hardware interface.
-> okay, that's something I didn't know, thought this was equal for all hardwares**_
if you change the engine sound then you must adapt the picth so that it matches the rpm.
-> I will ;)
i'm not sure why you changed the empty weight (even if there are numbers around 1060 floating around), you must not forget the weight of the equipment (radios, etc.).
-> Oops, forgotten it, I just thought 1111 was very high (a 4-seat DR400 is 1212) and found a number of 1060, but as you've explained I'll change it back :D

**Comment by ghost** [comment]
Where to change controls.startEngine??

**Comment by ghost** [comment]
Commit 3d31438 should fix
empty weight
engine sound

**Comment by D-ECHO** [comment]
On the wiki they say
[code]Another common element is the <mod-up> event, which happens when the button is released. For example, the S key fires the starter only as long as it is held down, via complementary commands on press and release:

 <key n="115">
  <name>s</name>
  <desc>Fire Starter on Selected Engine(s)</desc>
  <binding>
   <command>nasal</command>
   <script>controls.startEngine(1)</script>
  </binding>
  <mod-up>
   <binding>
    <command>nasal</command>
    <script>controls.startEngine(0)</script>
   </binding>
  </mod-up>
 </key>
[/code]... :(

**Comment by ghost** [comment]
@Harald67 could you help me how to change controls.startEngine pls?

**Comment by Harald67** [comment]
in c150.nas you can add a function like

controls.startEngine = func(n) {
    setprop("/controls/engines/engine/starter-key", n);
}

That way we do not need to redefine the standard 's' keyboard binding, so if someone is calling the startEngine function from a joystick button definition if will still work.

**Comment by ghost** [comment]
Should be fixed with last commit

**Comment by ghost** [comment]
Shall I merge this now?

**Comment by gilbertohasnofb** [comment]
@D-ECHO just saying, but I think we should adopt the policy of never merging our own PRs (that's at least how we do in the c172p and c182s projects). The idea is that a PR should be revised, and it's much easier for a different person to spot mistakes and bugs than the one who implemented it. Also, there might be things in your way of testing that are different than mine (maybe we tend to use different weather scenarios, maybe airports at different altitudes) which can easily make a bug spotable by one while not by the other. So even if people are slow for reviewing and testing, I would say to really wait for it, nobody will forget any PR behind, ok?

**Comment by gilbertohasnofb** [comment]
Also, I believe this PR broke two sounds that I had implemented:
- the parking brake sound is being used for the primer. I don't think a primer lever would make such a sound, so I would like that being reverted
- the engine sound is _really_ lower in pitch, it sounds like the engine is about to die when at idle. Please revert to the previous sounding setting

**Comment by ghost** [comment]
ok sry will revert in two weeks when back

---

Gesendet mit der Telekom Mail App
http://www.t-online.de/service/redir/email_app_android_sendmail_footer.htm

--- Original-Nachricht ---
Von: Gilberto Agostinho
Betreff: Re: [Harald67/c150] New starter system, split lever sound (#38)
Datum: 12.08.2016, 22:21 Uhr
An: Harald67/c150
Cc: D-ECHO, Mention

Also, I believe this PR broke two sounds that I had implemented:

```
* the parking brake sound is being used for the primer. I don't think a
  primer lever would make such a sound, so I would like that being
  reverted
* the engine sound is really lower in pitch, it sounds like the engine
  is about to die when at idle. Please revert to the previous sounding
  setting
```

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/Harald67/c150/pull/38#issuecomment-239550425 , or 
mute the thread

**Comment by gilbertohasnofb** [comment]
I will do it myself then

**Comment by gilbertohasnofb** [comment]
Another issue that I believe was caused by this PR: if you turn the engine on then flick the landing light switch, you get an error message about circuit breaks, which haven't been implement yet:

fgfs-screen-001

@Harald67 would you mind taking a look at this? I am leaving now and I won't be back until tomorrow night

**Comment by gilbertohasnofb** [comment]
@D-ECHO One more thing about PRs: please do not push a lot of unrelated work in a single PR because it makes it very confusing to review and even worse to revert something. In this PR you did modifications to the windows (3D model + animations) then worked with sound (sounds xml, wav files, a tiny bit of Nasal code), then added circuit breaks (xml). This should have been done in 3 PRs. And it's also nice if you open an issue before (such as you did for the window), then create a PR which once merged will close that issue, as this keeps things much more organized. 

Please do not take these comments the wrong way, I am glad to see contributions to any project I participate, I just want to share these "guidelines" which make life easier for all of us, ok? :smile: :cookie:

**Comment by Harald67** [comment]
The landing light problem was already there, I'll adjust the power consumption.

**Pull request merged**
